apiVersion: v1
kind: ConfigMap
metadata:
  name: lab37-web-config
  namespace: lab37
data:
  LAB_ENV: "lab"
  PORT: "8080"
  REDIS_HOST: "lab33-redis.lab33-storage.svc.cluster.local"
  REDIS_PORT: "6379"
  REDIS_DB: "0"
