apiVersion: v1
kind: Service
metadata:
  name: lab37-web
  namespace: lab37
  labels:
    app: lab37-web
spec:
  type: ClusterIP
  selector:
    app: lab37-web
  ports:
    - name: http
      port: 8080
      targetPort: 8080
