apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: lab35-read-all
rules:
  - apiGroups: [""]
    resources: ["pods", "services", "namespaces"]
    verbs: ["get", "list", "watch"]
  - apiGroups: ["apps"]
    resources: ["deployments", "statefulsets", "daemonsets"]
    verbs: ["get", "list", "watch"]
