apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: lab27-reader-binding
  namespace: lab27
subjects:
  - kind: ServiceAccount
    name: lab27-reader
    namespace: lab27
roleRef:
  kind: Role
  name: lab27-configmap-reader
  apiGroup: rbac.authorization.k8s.io
