apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: lab27-configmap-reader
  namespace: lab27
rules:
  - apiGroups: [""]
    resources: ["configmaps"]
    verbs: ["get", "list", "watch"]
