apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: lab35-configmap-editor-binding
  namespace: lab35-rbac
subjects:
  - kind: ServiceAccount
    name: lab35-config-editor
    namespace: lab35-rbac
roleRef:
  kind: Role
  name: lab35-configmap-editor-role
  apiGroup: rbac.authorization.k8s.io
