apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: lab35-configmap-editor-role
  namespace: lab35-rbac
rules:
  - apiGroups: [""]
    resources: ["configmaps"]
    verbs: ["get", "list", "watch", "create", "delete", "update", "patch"]
