global:
  scrape_interval: 15s           # как часто опрашиваем
  evaluation_interval: 15s       # как часто считаем правила/запросы
  external_labels:
    cluster: "ubuntu-nginx"

rule_files:
  - /etc/prometheus/alert.rules.yml

scrape_configs:

  - job_name: 'prometheus'
    static_configs:
      - targets: ['127.0.0.1:9090']
        labels:
          instance: 'local'

  - job_name: 'node'
    static_configs:
      - targets: ['127.0.0.1:9100']
        labels:
          instance: 'local'

  - job_name: 'nginx'
    static_configs:
      - targets: ['127.0.0.1:9113']
        labels:
          instance: 'local'
