apiVersion: v1
kind: Pod
metadata:
  name: pvc-test
  namespace: lab33-storage
spec:
  containers:
  - name: test
    image: busybox
    command: ["sh", "-c", "echo hello > /data/test.txt && sleep 3600"]
    volumeMounts:
    - name: backup
      mountPath: /backup
  volumes:
  - name: backup
    persistentVolumeClaim:
      claimName: lab34-redis-backup-pvc
