apiVersion: batch/v1
kind: Job
metadata:
  name: lab34-success
  namespace: lab34-jobs
  labels:
    job: lab34-success
    tier: backend
spec:
  backoffLimit: 0   # only in lab
  template:
    metadata:
      labels:
        job: lab34-success
        tier: backend
    spec:
      restartPolicy: Never
      containers:
        - name: success
          image: alpine:3.20
          command: ["/bin/sh", "-c"]
          args:
            - |
              echo "Lab34 starting Job...";
              sleep 5;
              echo "Success! k8s Job completed...";
