apiVersion: v1
kind: Service
metadata:
  name: lab33-redis
  namespace: lab33-storage
  labels:
    app: lab33-redis
spec:
  type: ClusterIP
  selector:
    app: lab33-redis
  ports:
    - name: redis
      port: 6379
      targetPort: 6379
