apiVersion: v1
kind: Service
metadata:
  name: lab34-web
  namespace: lab34-jobs
  labels:
    app: lab34-web
spec:
  type: ClusterIP
  selector:
    app: lab34-web
  ports:
    - name: http
      port: 8080
      targetPort: 8080
