apiVersion: apps/v1
kind: Deployment
metadata:
  name: lab34-web
  namespace: lab34-jobs
  labels:
    app: lab34-web
spec:
  replicas: 1
  selector:
    matchLabels:
      app: lab34-web
  template:
    metadata:
      labels:
        app: lab34-web
        service: labweb
        env: lab
    spec:
      containers:
        - name: web
          image: ghcr.io/vlrrbn/lab30-web-metrics:0.2.1
          imagePullPolicy: IfNotPresent
          envFrom:
            - configMapRef:
                name: lab33-web-config
          ports:
            - containerPort: 8080
          readinessProbe:
            httpGet:
              path: /health
              port: 8080
            initialDelaySeconds: 5
            periodSeconds: 5
          livenessProbe:
            httpGet:
              path: /health
              port: 8080
            initialDelaySeconds: 15
            periodSeconds: 10
