apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: lab34-web
  namespace: lab34-jobs
  annotations:
    nginx.ingress.kubernetes.io/rewrite-target: /
spec:
  ingressClassName: nginx
  rules:
    - host: lab30.local
      http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: lab34-web
                port:
                  number: 8080
