apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: lab36-ingress
  namespace: lab36-netpol
spec:
  ingressClassName: nginx
  rules:
    - host: lab36-backend.local
      http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: lab36-backend
                port:
                  number: 80
