apiVersion: apps/v1
kind: Deployment
metadata:
  name: lab32-memhog
  namespace: lab32-resources
  labels:
    app: lab32-memhog
spec:
  replicas: 1
  selector:
    matchLabels:
      app: lab32-memhog
  template:
    metadata:
      labels:
        app: lab32-memhog
    spec:
      containers:
        - name: memhog
          image: polinux/stress
          command: ["stress"]
          args:
            - "--vm"
            - "1"
            - "--vm-bytes"
            - "256M"
            - "--vm-hang"
            - "1"
          resources:
            requests:
              memory: "64Mi"
              cpu: "50m"
            limits:
              memory: "124Mi"
              cpu: "200m"
