apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: APP_NAME-ca
  namespace: APP_NAMESPACE
spec:
  isCA: true
  commonName: APP_NAME-ca
  secretName: APP_NAME-ca
  duration: Hours
  renewBefore: Hours
  issuerRef:
    name: APP_NAME-selfsigned
    kind: ClusterIssuer
