apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: APP_NAME
  namespace: APP_NAMESPACE
spec:
  secretName: APP_NAME-tls
  duration: Hours
  renewBefore: Hours
  issuerRef:
    name: APP_NAME-issuer
    kind: Issuer
  dnsNames:
    - APP_HOST
