apiVersion: batch/v1
kind: Job
metadata:
  name: APP_NAME-job
  namespace: APP_NAMESPACE
spec:
  backoffLimit: 3
  template:
    metadata:
      labels:
        app: APP_NAME
    spec:
      restartPolicy: Never
      containers:
        - name: APP_NAME
          image: APP_IMAGE
          imagePullPolicy: IfNotPresent
          command: ["/bin/sh", "-c"]
          args: ["echo hello from job; sleep 5"]
