apiVersion: networking.k8s.io/v1
kind: NetworkPolicy
metadata:
  name: allow-from-namespace
  namespace: APP_NAMESPACE
spec:
  podSelector:
    matchLabels:
      app: APP_NAME
  policyTypes:
    - Ingress
  ingress:
    - from:
        - podSelector: {}
