apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: APP_NAME-role
  namespace: APP_NAMESPACE
rules:
  - apiGroups: [""]
    resources: ["pods", "services", "configmaps", "secrets"]
    verbs: ["get", "list", "watch"]
