apiVersion: v1
kind: Service
metadata:
  name: APP_NAME
  namespace: APP_NAMESPACE
  labels:
    app: APP_NAME
spec:
  type: ClusterIP
  selector:
    app: APP_NAME
  ports:
    - name: http
      port: APP_PORT
      targetPort: APP_PORT
