galaxy_info:
  role_name: lab_common
  namespace: vlrrbn
  author: Vlrrbn
  description: Common stuff for lab
  company: Microsoft
  license: MIT-0
  min_ansible_version: "2.1"
  galaxy_tags: []

dependencies: []
