---
lab_common_packages:
  - curl
  - vim
  - htop

lab_common_user: "labops_user"
lab_common_group: "labops_group"
lab_common_create_user: true

lab_common_motd_enabled: true
lab_common_motd_message: "Welcome to lab host (managed by lab_common)"

lab_common_sudo_enabled: false
lab_common_sudo_nopass: true
lab_common_sudo_commands:
  - ALL
