apiVersion: v1
kind: Service
metadata:
  name: lab27-redis
  namespace: lab27
  labels:
    app: lab27-redis
spec:
  type: ClusterIP
  selector:
    app: lab27-redis
  ports:
    - name: redis
      port: 6379
      targetPort: 6379
