apiVersion: v1
kind: Service
metadata:
  name: lab27-web
  namespace: lab27
  labels:
    app: lab27-web
spec:
  type: ClusterIP
  selector:
    app: lab27-web
  ports:
    - name: http
      port: 8080
      targetPort: 8080
