apiVersion: apps/v1
kind: Deployment
metadata:
  name: lab27-web
  namespace: lab27
  labels:
    app: lab27-web
    tier: frontend
spec:
  replicas: 1
  selector:
    matchLabels:
      app: lab27-web
  template:
    metadata:
      labels:
        app: lab27-web
        tier: frontend
        service: labweb
        env: lab
    spec:
      containers:
        - name: web
          image: lab25-web-workflows:dev
          imagePullPolicy: IfNotPresent
          envFrom:
            - configMapRef:
                name: lab27-web-config
            - secretRef:
                name: lab27-web-secret
          ports:
            - containerPort: 8080
          readinessProbe:
            httpGet:
              path: /health
              port: 8080
            initialDelaySeconds: 5
            periodSeconds: 5
          livenessProbe:
            httpGet:
              path: /health
              port: 8080
            initialDelaySeconds: 15
            periodSeconds: 10
