server:
  http_listen_port: 9080
  grpc_listen_port: 0

clients:
  - url: http://loki:3100/loki/api/v1/push

positions:
  filename: /positions/positions.yaml

scrape_configs:

  - job_name: nginx
    static_configs:
      - targets: [localhost]
        labels:
          job: nginx
          __path__: /var/log/nginx/access.json
    pipeline_stages:
      - json:
          expressions:
            time: time
            remote_addr: remote_addr
            request: request
            status: status
            bytes_sent: bytes_sent
            upstream_addr: upstream_addr
            upstream_status: upstream_status
            request_time: request_time
            upstream_response_time: upstream_response_time
      - labels:
          status:
          upstream_status:
      - timestamp:
          source: time
          format: RFC3339Nano
          fallback_formats:
            - RFC3339
            - Unix
            
  - job_name: auth
    static_configs:
      - targets: [localhost]
        labels:
          job: auth
          __path__: /hostlog/auth.log
    pipeline_stages:
      - match:
          selector: '{job="auth"} |= "Failed password"'
          stages:
            - regex:
                expression: 'Failed password for(?: invalid user)? (?P<user>\S+) from (?P<ip>\S+)'
            - labels:
                user:
                ip:
