apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: lab27

resources:
 - namespace.yaml
 - redis-deployment.yaml
 - redis-service.yaml
 - web-deployment.yaml
 - web-service.yaml
 - web-config.yaml

labels:
 - includeSelectors: true
   pairs:
    env: lab
    managed-by: kustomize
