apiVersion: v1
kind: ConfigMap
metadata:
  name: lab27-web-config
  namespace: lab27
data:
  LAB_ENV: "lab"
  PORT: "8080"
  REDIS_HOST: "lab27-redis"
  REDIS_PORT: "6379"
  REDIS_DB: "0"
  FEATURE_FLAG_SHOW_HITS: "true"

---
apiVersion: v1
kind: Secret
metadata:
  name: lab27-web-secret
  namespace: lab27
type: Opaque
stringData:
  APP_SECRET_KEY: "secret-key-lab27"
  FAKE_API_TOKEN: "fake-token-lab27"
