apiVersion: v1
kind: Service
metadata:
  name: lab30-redis
  namespace: lab30
  labels:
    app: lab30-redis
spec:
  type: ClusterIP
  selector:
    app: lab30-redis
  ports:
    - name: redis
      port: 6379
      targetPort: 6379
