apiVersion: apps/v1
kind: Deployment
metadata:
  name: lab30-web
  namespace: lab30
  labels:
    app: lab30-web
    tier: frontend
spec:
  replicas: 1
  selector:
    matchLabels:
      app: lab30-web
  template:
    metadata:
      labels:
        app: lab30-web
        tier: frontend
        service: labweb
        env: lab
    spec:
      containers:
        - name: web
          # Non-existent tag â†’ ImagePullBackOff
          image: ghcr.io/vlrrbn/lab30-web-metrics:does-not-exist
          imagePullPolicy: Always
          envFrom:
            - configMapRef:
                name: lab30-web-config
          ports:
            - containerPort: 8080
          readinessProbe:
            httpGet:
              path: /health
              port: 8080
            initialDelaySeconds: 5
            periodSeconds: 5
          livenessProbe:
            httpGet:
              path: /health
              port: 8080
            initialDelaySeconds: 15
            periodSeconds: 10
