apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

# namePrefix: dev-
# namespace: lab27

resources:
  - ../../base

patches:
  - path: patch-web-replicas.yaml
    target:
      kind: Deployment
      name: lab27-web
