apiVersion: v1
kind: Service
metadata:
  name: lab36-backend
  namespace: lab36-netpol
  labels:
    app: lab36-backend
spec:
  type: ClusterIP
  selector:
    app: lab36-backend
  ports:
    - name: http
      port: 80
      targetPort: 80
      protocol: TCP
