kind: Cluster
apiVersion: kind.x-k8s.io/v1alpha4
name: lab27
nodes:
  - role: control-plane
    extraPortMappings:
      # Optional: map NodePort range
      # - containerPort: 30080
      #   hostPort: 30080
      #   protocol: TCP
